# Generated by Django 5.2.7 on 2025-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertiesApp', '0002_dwelling_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.DecimalField(decimal_places=0, max_digits=7)),
                ('major', models.CharField(max_length=50)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
