# Generated by Django 5.2.7 on 2025-11-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertiesApp', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mymedia/images/'),
        ),
    ]
