# Generated by Django 5.2.7 on 2025-11-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertiesApp', '0004_alter_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
